project:
  type: website

website:
  title: "Bayesian Thinking"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
 
format:
  html:
    theme: journal
    
execute:
  freeze: auto
  
  
  
  