---
title: "Normal-Normal Model"
format: 
  html:
    embed-resources: true
execute:
  echo: true
  warning: false
  message: false
editor: source  
---

**Objective:** 

- By the end of this lesson, students will have reviewed the following topics:

    - When to implement the normal-normal model
    
    - How to implement the normal-normal model
    
    - How to disseminate analysis results

**Duration:** 

- 75 minutes

**Materials:**

- Handouts with exercises and problems related to basic probability
- Computer, projector, and screen

**Introduction:**



**Introduce the lesson's topic:** 



**Main Content:** 

#### The Normal Model

Recall the normal model,

$$f(y) = \frac{1}{\sqrt{2\pi\sigma^2}} \exp\left\{-\frac{\left(y - \mu\right)^2}{2\sigma^2} \right\}$$

where $y$ is a continuous random variable that can take any value in $\mathbb{R}$; i.e., $Y \in \left(-\infty, \infty\right)$.

Suppose we have $n$ observations, then the joint distribution is given by

$$f(\overset{\to}{y}|\mu) = \prod_{i=1}^n f(y_i|\mu) = \prod_{i=1}^n \frac{1}{\sqrt{2\pi\sigma^2}} \exp\left\{-\frac{\left(y_i - \mu\right)^2}{2\sigma^2} \right\}$$

Then the likelihood is given by,

$$
\begin{align*}
L(\mu| \overset{\to}{y}) &\propto \prod_{i=1}^n \exp\left\{-\frac{\left(y_i - \mu\right)^2}{2\sigma^2} \right\} = \exp\left\{-\frac{\sum_{i=1}^n \left(y_i - \mu\right)^2}{2\sigma^2} \right\} \\
&\propto \exp\left\{-\frac{\left(\bar{y} - \mu\right)^2}{2\sigma^2/n} \right\} 
\end{align*}
$$

#### The Normal-Normal Model

- Let $\mu \in (-\infty, \infty)$ be an unknown mean parameter and $(Y_1, Y_2, ..., Y_n)$ be an independent $N(\mu, \sigma^2)$, where $\sigma$ is assumed to be known.

- The Normal-Normal Bayesian model has Normal distributions for both prior and data. The Normal prior is on the unknown mean, $\mu$.

$$Y_i | \mu \overset{\text{ind}}{\sim} N(\mu, \sigma^2)$$

$$\mu \sim N(\theta, \tau^2)$$

- When we have data $\overset{\to}{y} = (y_1, ..., y_n)$ with mean $\bar{y}$, the posterior distribution for $\mu$ is also Normal with updated parameters,

$$\mu|\overset{\to}{y} \sim N\left( \theta \frac{\sigma^2}{n\tau^2 + \sigma^2} + \bar{y} \frac{n\tau^2}{n\tau^2+\sigma^2}, \frac{\tau^2 \sigma^2}{n\tau^2 + \sigma^2} \right)$$


**Calculation and Practice:**

- Example 1: concussions

- Example 2: stock prices

**Discussion and Wrap-Up:**

- Facilitate a class discussion to review the example problems, reinforce key concepts, and answer any questions the students have.

**Homework:**

- Assign additional problems to practice the basic probability rules.

**Formative Assessment:**

- Evaluate students based on their participation in discussions, their ability to solve example problems, and their performance on the assigned homework.

**Conclusion:**

- Our goal is to analyze in the best way possible. 